### ISSUE TITLE
obrazky z datasetu

### ISSUE THREAD

**Issue by dmacjam** [SittingHamsters/Prototype#3]
Nebolo by dobre zatial na testovanie si len pytat obrazky z datasetu?

**Comment by dmacjam** [comment]
Spravil som novu blackboard testovaciu, zatial mi nacitava moje grayscale obrazky. Este mi tu ale chyba ze log sa nescroluje, ked sa nieco nove vypise.

**Comment by fadawar** [comment]
Matej to už spravil. Dá sa vybrať priečinok s dátami. Taktiež aj log sa už automaticky scrolluje.
