### ISSUE TITLE
ObservableCollection<ResultMessage> Memory nie je Thread safe!

### ISSUE THREAD

**Issue by ametj** [SittingHamsters/Prototype#33]

**Comment by fadawar** [comment]
Popíš prosím bližšie problém. Je to totižto robené tak, aby to bolo thread safe. Ako si sa dopracoval k tomu, že to nie je thread safe? Podľa čoho si to diagnostikoval? Vieš určiť, v ktorej časti kódu sa to kazí? Mám dojem, že nám to doteraz fungovalo, i keď možnože to bola len náhoda.

**Comment by fadawar** [comment]
Mal si pravdu Matej. Teraz som si o tom hľadal niečo na internete a budeme to musieť spraviť inak. Dobre, že si to našiel. Označujem to ako bug.

Mimochodom, prečo v Microsofte urobia funkciu nazvanú EnableCollectionSynchronization, ktorá nerobí to čo sa od nej očakáva? Dovolí pristupovať ku kolekcii aj z iných vlákien (nití), ale nezabezpečujú synchronizáciu (i keď to majú v názve). Katastrofa :disappointed:

**Comment by ametj** [comment]
Pokiaľ som správne pochopil tak zabezpečí len to aby sa na UI threade vykonali eventy. Ten lock čo sa tam dal ako parameter budeme musieť použiť pri prístupe k Memory. Vzhľadom na to, že prvky len pridávame tak zatiaľ by malo stačiť 

```
lock (memoryLock){
  Memory.Add(...)
}
```
